language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.2
cache: bundle
before_script: bin/rake db
script: bin/rake test
addons:
  codeclimate:
    repo_token:
      secure: CxFMGcOhwkzowVZyys4fxSlsahNTNR6eBnRJmXqOhzjZwOoB7z0j3wfvIv8lDkKl03ayFUmToH147M4euh6RTbyCiFa9ti/bcVglWHaTDn6Qh5Ow6FWSJ76tIPAXpDaipn+ns8PQpsvrBISu6pB0MTgBbMwGQLpEUbDKtOCxexY=
deploy:
  provider: rubygems
  api_key:
    secure: Ss+mExNaQHwVyJ0u5cN/BrrVEPZPUdojUxbVj5xa4fjT8OCmaeXY6DM24L1dDpysNLlExKzNVzK6JZNl1KFE03U6Be+S8sr5yJ3hlhPIqShA21+riiC/yeEnNw9oWv+EDDw2CD5TImF3u4YmGJohVdpCGl2U3tlRP5Kchz1vYjw=
  gem: controller_resources
  on:
    tags: true
    repo: tubbo/controller_resources
